services:
    php:
        build:
            context: docker/php
        volumes:
            - ./:/var/www/:cached
        ports:
            - 80:8000

    node:
        build:
            context: docker/node
        volumes:
            - ./:/var/www:cached
        ports:
            - 5173:5173

    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
